# Conclusion/ Discussion {#conclusion} 
From our analysis for this project, we found that national security contributes significantly to California’s economy. The total impact appears similar to high profile sectors such as the agriculture and film industries. In 2019, the federal government invested at least $47.0 billion and directly employed approximately 348,000 residents in the state. This resulted in $181.2 billion in economic impact and supported over 792,000 full-time equivalent jobs in California. 

Our process for this project provided us with some lessons:

- FOIA data can be difficult to obtain, as it is dependent on how quickly and accurately a federal agency responds to your request. From our experience, we have received responses to our FOIA requests at least six months after our initial submission.However, data obtained from FOIAs (SmartPay) constituted 3.4% of the nation’s national security-related direct spending. Depending on your resources and priorities, choosing to omit this data would typically have minimal impacts on the overall estimates. 
- Manually obtaining and processing government spending data (such as USAspending) is time and labor intensive. In developing an automated way of making this more efficient, we found that there were not a lot of good resources on how to interact with APIs for the initial data grab. The APIs that exist do not have clear instructions, and it takes time to learn how to interact with them. Even in automating this process, the limitation of time and labor presents itself. As a caution, take ample time to understand the APIs to ensure the correct data is obtained, especially if branching out from the API used for this study.    
- Within the manually processing of government spending data, a particular pain point was the remediation of errors in the USAspending data. Contracts data may have had old, mistyped, or missing NAICS codes that required additional searching of previous crosswalks to properly allocate spending entries to the correct IMPLAN code. Additionally, the errors of missing or “90” congressional district values require diligence in approach to remediate that issue. 
- Processing this data in IMPLAN for the county and congressional district models can be time consuming, and approximate time will vary based on the number of counties and congressional districts being processed.  

For researchers looking to perform this study on their own, we hope to offer some advice on the planning and timeline stages for such a project: 

- If it is determined that FOIA data is wanted and/or needed for your study, file your requests many months in advance. 
- Running the code up to the aggregate function [REFERENCE TO METHOD SECTION] and looking at how many IMPLAN sectors have a spending amount should provide a good barometer for how long the IMPLAN processing will take for the statewide model. The California statewide model had 400 IMPLAN sectors and took roughly 20 minutes to run. 
- After running the for-loop code [REFERENCE TO METHOD SECTION] for generating localized IMPLAN activity sheets, note that the activity sheets for the multi-region inverse models will take significantly more time than the sheets for the normal models. Roughly speaking, a single inverse model takes a couple of hours to finish running, while a single region model should complete within half an hour. 

The process guide for this study was created to be a useful tool for researchers to conduct similar economic impact studies. Through this document, we hope that additional quality studies continue to come about and assist in making government spending data more readily accessible and transparent. Furthermore, we hope to continue making process improvements in order to ensure that this study retains its functionality and capacity for future years. 
