--- 
title: "California Military Economic Impact Study Process Guide"
author: "Britnee Pannell & Sumeet Bedi"
date: "`r Sys.Date()`"
description: This GitBook explains the process used to develop the 2020 California Military Economic Impact Study. 
documentclass: book
github-repo: bnpannell/MEIS_Documentation
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
---

# Introduction

*Introduce the project.* 
*Add blurb about the history of the project and how it has evolved since then.*  

*- Who is funding project* 
*- Where is the focus of the project?* 
*- When does the project take place?* 
*- How does the project get accomplished? (rough overview)*

*Why are we doing this project? What does it hope to answer?* 
*Specifically mention this documentation is to allow other areas/states to have a path to follow if they wish to duplicate this work.*

*This also serves to document and justify our conclusions in the main reports if anyone wants to 'check our work.'*

The California Military Economic Impact Study report series began in 2018, when the California Governor's Office of Planning & Research and the Governor's Military Council requested the California Research Bureau (a unit of the California State Library) to conduct this study. This report provides detailed statewide and localized economic impacts of federal national security activity in the state of California. The federal agencies identified as relevant to national security includes the Departments of Defense, Homeland Security, Veterans Affairs, and specified sub-agencies of Energy. The type of economic activity detailed includes spending (contracts, grants, veterans' benefits, and SmartPay charge card) and employment data (civilian and military).  The first report, published in August 2018, utilized federal fiscal year 2016 data, while the second report, published in December 2019, used fiscal year 2018 data. 

Following these 2 reports, the Office of Planning & Research and the Research Bureau secured grant funding from the Department of Defense to support two full-time equivalent (FTE) positions to develop supplemental reports that help localize the economic impacts detailed in the statewide report. In December 2020, the Research Bureau produced the 2020 California Military Economic Impact Study, and followed this third edition of the statewide report with 2 first-time supplements that discuss the economic impacts in every county and congressional district in California. In December 2021, the Research Bureau completed the fourth version of the statewide report as well as the second edition of the county and congressional district supplements. After completion of the second round of supplements, the Research Bureau was tasked with producing this process guide document.

This process guide and supporting documentation were developed in order to allow other states to replicate the methodology of this study for their respective geography of interest. Additionally, this documentation serves to provide the rationale behind how the data was gathered, wrangled, and analyzed in order to justify the conclusions in our main reports.
